### ISSUE TITLE
Syntax Bug: Closing parenthesis after inline module 

### ISSUE THREAD

**Issue by jsiebern** [BuckleScript/syntax#16]
I came across a nasty bug just now. I'm not sure if it's just this specific setup though. Some code of mine compiled fine but didn't work the way I expected. When I checked the JS Code, I found it was missing everything after a certain point (Still, it compiled fine).

I eventually found one closing parenthesis too much after a module definition.
See the following example:
```reason
open Ws

let wss = Server.make({port: 82})
let address = wss->Server.address
let log = msg => Js.log(`> Server: ${msg}`)
log(`Running on: ${address.address}:${address.port->string_of_int} (${address.family})`)

module ClientSet = {
  module T = Belt.Id.MakeComparable({
    type t = Client.t;
    let cmp = (a, b) => {
      compare(a->Client.getUniqueId, b->Client.getUniqueId);
    };
  });

  let empty = Belt.Set.make(~id=module (T));


}); // this ")" here, this can even be "))))))))))))))))" and it still compiles without complaint

Js.log("test"); // Is omitted from the compiled JS
```

Addition: When I run the file through `napkinscript.exe -parse ns -print ns`, everything after the module closing `}` gets deleted from it

**Comment by cristianoc** [comment]
Shorter version

```
module C = {
  module T = Fun({
      foo(a+c, b+c)
  })
}
)
Js.log("test"); // Is omitted from the compiled JS
```

**Comment by cristianoc** [comment]
Issue: `parseImplementation`, and I guess `parseInterface` should check when last token is not `eof`, and act accordingly.

**Comment by IwanKaramazow** [comment]
Thanks for the report @jsiebern! This turned out to be a one-liner.

@cristianoc turns out I forgot an `eatBreadcrumb`, giving the wrong parsing context during the error.
Proves again that I should implement your suggestion of `make eatBreadcrumb also take a grammar, so it's easier to check that the calls are matching`
