### ISSUE TITLE
Converting regex statement

### ISSUE THREAD

**Issue by believer** [BuckleScript/syntax#3]
This regex statement gives me all kinds of errors

```reason
let titleRegex = %re({|/((^[a-zåäö\-\:\s]+\d{1,}[:-]?\w?)|^[a-zåäö]+)|(([a-zåäö\-\/]\s?)+,\s([a-zåäö\-]\s?)+)|([a-zåäö/]+ till salu)/ig|})
```

It seems like it's giving me two errors for **åäö**, one empty error and one highlighting the actual character.

![Screenshot 2020-07-02 08 23 46](https://user-images.githubusercontent.com/1478102/86323676-9100d800-bc3d-11ea-9bc5-c5635648d82a.png)
![Screenshot 2020-07-02 08 23 51](https://user-images.githubusercontent.com/1478102/86323679-92320500-bc3d-11ea-8f98-15a947bfc565.png)
![Screenshot 2020-07-02 08 23 57](https://user-images.githubusercontent.com/1478102/86323680-92ca9b80-bc3d-11ea-812a-5c8fffc07f71.png)
![Screenshot 2020-07-02 08 24 05](https://user-images.githubusercontent.com/1478102/86323683-93633200-bc3d-11ea-859c-5ef4bd35bfd1.png)
![Screenshot 2020-07-02 08 24 11](https://user-images.githubusercontent.com/1478102/86323685-93633200-bc3d-11ea-8d67-8c4f1f8b5d7d.png)
![Screenshot 2020-07-02 08 24 18](https://user-images.githubusercontent.com/1478102/86323688-93fbc880-bc3d-11ea-9bef-4745038ec4ab.png)
![Screenshot 2020-07-02 08 24 23](https://user-images.githubusercontent.com/1478102/86323690-93fbc880-bc3d-11ea-9e7c-01e5823a0ffd.png)
![Screenshot 2020-07-02 08 24 31](https://user-images.githubusercontent.com/1478102/86323691-94945f00-bc3d-11ea-842c-e8b18999146d.png)

**Comment by thislogancall** [comment]
Looks like this works, 
```reason
let titleRegex = %re(`/((^[a-zåäö\-\:\s]+\d{1,}[:-]?\w?)|^[a-zåäö]+)|(([a-zåäö\-\/]\s?)+,\s([a-zåäö\-]\s?)+)|([a-zåäö/]+ till salu)/ig`)
```

`{||}` strings seem to be completely replaced with ``

**Comment by believer** [comment]
Thanks @thislogancall! This was indeed the same issue as #4
