### ISSUE TITLE
SwiftUI like trailing closures/expressions

### ISSUE THREAD

**Issue by jfrolich** [BuckleScript/syntax#30]
JSX is amazing for building UIs. Especially when they are deeply nested. SwiftUI is using some more familiar language elements to make nested declarative UIs even more readable with trailing closures. It might be interesting to consider a syntax like this for Bucklescript as most people use it for building UIs.

```swift
NavigationView {
    List {
        Text("Hello World")
        Text("Hello World")
        Text("Hello World")
    }
}
```

```reason
@react.component
let make = () => {
   NavigationView {
     List(~color=`red) {
        [|
          Text("Hello World"),
          Text("Hello World"),
          Text("Hello World"),
        |]
     }
   }
}
```

Whereby the behavior of this is configurable just like JSX. In this case, the trailing expression could be passed as the `~children` argument to the `make` function.

**Comment by alexeygolev** [comment]
@jfrolich I thought it looked familiar. And indeed Scala has a similar syntactic feature

**Comment by IwanKaramazow** [comment]
Gonna close this one for now. Without the skin in the game of a real product backing this feature, it's gonna add to the maintenance burden and complexity of the language. The product is the driver.

**Comment by jfrolich** [comment]
> Gonna close this one for now. Without the skin in the game of a real product backing this feature, it's gonna add to the maintenance burden and complexity of the language. The product is the driver.

Thanks for the feedback, I am not sure what you mean by this. I would like to adopt this in my product, or make it work with React instead of JSX, but how can we adopt it with a product if it doesn't exist?
