### ISSUE TITLE
Converting bs.raw

### ISSUE THREAD

**Issue by believer** [BuckleScript/syntax#4]
I'm trying to convert a `bs.raw` binding to the new syntax but can't get it working correctly. This might be related to #3 which also uses the `{|val|}` syntax, so might be something there?

```reason
let environment = %bs.raw({|process.env.NODE_ENV|})
```

```
3 │    | Production
4 │
5 │  let environment = %bs.raw({|process.env.NODE_ENV|})
                                                       ^
6 │
7 │  let make = () =>

Did you forget a `.` here?
```

**Comment by IwanKaramazow** [comment]
The equivalent syntax would be ``let environment = %bs.raw(`process.env.NODE_ENV`)``

**Comment by believer** [comment]
Perfect, thanks @IwanKaramazow!
