### ISSUE TITLE
Uppercase generics not allowed

### ISSUE THREAD

**Issue by jsiebern** [BuckleScript/syntax#49]
I'm wondering if that is intentional ( I haven't seen it in the change list):
```reason
module Test = {
  type x('A) = 'A;
  type y = x(string);
};
``` 
Old syntax is fine.

```reason
module Test = {
  type x<'A> = 'A;
  type y = x<string>;
};
```
New syntax says `[E] Line 2, 18: Did you forget a > here?`, where as `  type x<'a> = 'a;` works fine

**Comment by IwanKaramazow** [comment]
I did not know this was a thing. Very easy fix. Do you often use upper case generics?

**Comment by jsiebern** [comment]
Not necessarily, no. I'm working on that typescript conversion thing, and **they** do it a lot, that's how I stumbled across it in the first place! Still it works in current Reason & OCaml, so I believe it makes sense to continue to support it if it doesn't mess up the parser in any way.

**Comment by IwanKaramazow** [comment]
Yes, absolutely.
