### ISSUE TITLE
[printer] Superfluous brackets with ++ operator

### ISSUE THREAD

**Issue by cknitt** [BuckleScript/syntax#60]
```reason
let greet = (~firstName, ~lastName) => "Hello, " ++ firstName ++ " " ++ lastName;
```

gets printed as

```reason
let greet = (~firstName, ~lastName) => "Hello, " ++ (firstName ++ (" " ++ lastName))
```

by BS 8.1.1. yarn bsc -fmt.

**Comment by IwanKaramazow** [comment]
In the new `res` syntax, the associativity of `++` has been changed to left-to-right. This is to match the associativity as we're used to in JavaScript. Previously it was right-to-left, which is a bit counter-intuitive if you're coming from a javascript/typescript/go/swift/c… Hence the need for parens to express that right-to-left direction.

The extra parens when printing from Reason stems from the fact that we can't change the semantics of your program.
In theory it would be fine to drop the parens in your case. The semantics would be the same.
However you might have redefined `++` to have a totally different meaning which _might_ rely on the right-to-left semantics… Hence to preserve the semantics of your code we take the safe route, and just print the parens.

We would ask you to remove the parens manually.

**Comment by bloodyowl** [comment]
Maybe we could add a flag to the conversion script that states "I didn't override ++, it's safe the drop the parens"?

**Comment by cknitt** [comment]
@IwanKaramazow Thanks a lot for the explanation!
