### ISSUE TITLE
Add line directive syntax support

### ISSUE THREAD

**Issue by ryyppy** [BuckleScript/syntax#62]
In OCaml, you can tell the compiler to set the linenumber / filename for any code like this:

```
# 20 "playground.ml"
let _ = 1 + 1
```

In the new BuckleScript syntax, this construct (`# [linenum] "filename"`) doesn't exist.

**Use case**
In reasonml.org, we test compile our code snippets. Since we are using the line preview mode for errors, we'd like to inject the corrected line number and the filename via the directive before we compile each snippet. Would be great to have that feature available for `.res` snippets as well.

**Syntax**
I know that `#` is already reserved for poly-variants.. since this feature is not necessarily interesting for end users, i guess having less ergonomic syntax alternatives is okay as well

**Comment by IwanKaramazow** [comment]
**Proposed syntax**
```
//line :line
//line filename:line
/*line :line*/
/*line filename:line*/
```
example:
```
//line playground.res:10      the filename is playground.res, and the line number is 10 for the next line
```

**Background**
The line-directive alters the position of the character immediately after the line-directive. For a //line comment, this is the first character of the next line, and for a /*line comment this is the character position immediately following the closing */.
To distinguish line-directive comments from normal comments, there's no space between the comment opening and the name of the `line` directive. 
The advantages of reusing comments:
* keeps compatibility with the ocaml ast
* printer still works and is already done.

**Questions**
* Do we want to alter the column of the location, e.g. `//line filename:line:col`
* If no `filename` is given, do we re-use the name of the file or do we record an empty filename?
* filenames with a `:` should still work.
* Should we be pretty strict with spaces? `//line    \t     :line` or `//line filename    :     line` -> too many spaces, do not interpret as line directive?
* Should `//line filename:line`  always start a line? I.e. is this example weird:
```
let x = 1 //line playground.res:20
let y = 2
```

**Comment by jfrolich** [comment]
Perhaps nice to use the annotation syntax;

```
@line ("playground.res", 20)
let x = 1
```

**Comment by IwanKaramazow** [comment]
@jfrolich Not every ast node has attributes… It would immediately exclude using line-directives in some positions.

**Comment by jfrolich** [comment]
Ah ok interesting. So the compiler can attach the file/line number to any ast type with the comment syntax. Cool didn't know that!

**Comment by cristianoc** [comment]
Note this directive breaks all sorts of things and should be used sparingly.

**Comment by cristianoc** [comment]
@ryyppy what’s the extent of the use case? Set a single file name for a code snippet? Ie always at the top?

**Comment by ryyppy** [comment]
@cristianoc there are two concrete cases:
- playground: we need the directive to set the filename for error messages to values like `reasonml.org/try`
- Markdown examples: We iterate through each code snippet and need to apply the correct line number (starting from the line number inside the markdown file), and again the original markdown file name.

I know that I can set the filename via the syntax apis, but not the line number.

Any other solution that doesn't involve directive parsing is fine to me as well

**Comment by IwanKaramazow** [comment]
Implemented a different strategy in https://github.com/BuckleScript/syntax/pull/65/files
The idea is to not expose this through syntax at parse time, but allow (programmatic) users of the parser to seed the initial line number.
```ocaml
let parser = Napkin_parser.make ~line:2 mySourceCode myFilename
```
If there's anything else you need, let me know.
