### ISSUE TITLE
Matching polymorphic variant tags

### ISSUE THREAD

**Issue by jacobp100** [BuckleScript/syntax#7]
The syntax for matching a polymorphic variant type uses a double hashtag

```
type nums = [ | #one | #two | #three];

type alphas = [ | #a | #b | #c];

type alphanums = [ nums | alphas ];

let a: alphanums = #a;

switch a {
| ##alphas => Js.log("alphas")
| ##nums => Js.log("nums")
};
```

What if we used the spread operator? Either before or after the hashtag

```
switch a {
| #...alphas => Js.log("alphas")
| #...nums => Js.log("nums")
};
```

**Comment by IwanKaramazow** [comment]
@jacobp100 this is a very good idea. I'll implement this!

**Comment by jfrolich** [comment]
Yes more intuitive indeed!

**Comment by IwanKaramazow** [comment]
@jacobp100 Thanks for the wonderful idea. This has been implemented.
